import Circle from "@app/components/pointer/Circle";
import { useEffect, useRef } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const circleRef = useRef<any>();
  // circleRef.current = [];

  // useEffect(() => {
  //   const { innerWidth, innerHeight } = window;
  //   circleRef.current.forEach((ref: any) =>
  //     ref.moveTo(innerWidth / 2, innerHeight / 2)
  //   );

  //   const onMove = ({
  //     clientX,
  //     clientY,
  //   }: {
  //     clientX: number;
  //     clientY: number;
  //   }) => {
  //     circleRef.current.forEach((ref: any) => ref.moveTo(clientX, clientY));
  //   };

  //   window.addEventListener("pointermove", onMove);

  //   return () => window.removeEventListener("pointermove", onMove);
  // }, []);

  // const addCircleRef = (ref: any) => {
  //   if (ref) {
  //     circleRef.current.push(ref);
  //   }
  // };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ height: "200rem" }}>
        {/* <div style={{ padding: "10px",  }}>
          <p>Move your mouse around</p>
          <Circle size="sm" ref={addCircleRef} delay={0} />
          <Circle size="md" ref={addCircleRef} delay={0.1} />
          <Circle size="lg" ref={addCircleRef} delay={0.2} />
        </div> */}
      </main>
    </>
  );
}
